### ISSUE TITLE
Always same problem...

### ISSUE THREAD

**Issue by skerebere** [yurilaaziz/instabot.py#1]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x ] 3.x (3.6)

## Description of your issue

![sin titulo](https://user-images.githubusercontent.com/17657543/50830224-1d7b5480-133f-11e9-869d-de2979b8b781.png)

## Config

```
Same as original only change username and password
```

**Comment by yurilaaziz** [comment]
please create this issue to the main stream , https://github.com/instabot-py/instabot.py
