### ISSUE TITLE
How to use own tags? Where to change setting?

### ISSUE THREAD

**Issue by mbe9477** [yurilaaziz/instabot.py#18]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [X] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
Darwin xxx-iMac-2.fritz.box 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
3.7.3
```

#### Pip Version?
```
pip 19.2.3 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
```

#### Instabot Version?
```
Installed version 0.6.0
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [X] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
I like to use my own tags etc. 
Have changed them in "default_config.py" already. But it still likes "cat" tagged pics... 
I find no other file on the directory where anywhere is "cat" inside!? 

I am running the bot with this command:
instabot-py --login LOGIN --password PASSWORD -vv

```

#### Config

```

> sample.instabot.config.yml

---
login : "XXX"
password : "XXX"
debug: 0
follow_time: 604800
like_per_day: 300
comments_per_day: 70
max_like_for_one_tag: 36
follow_per_day: 100
follow_time: 36000
unfollow_per_day: 0
unfollow_break_min: 3
unfollow_break_max: 17
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: false

```

**Comment by Boxer1990** [comment]
got the same issue

**Comment by Orange06** [comment]
neo-instabot -c yourconfig.yml -vv
set your login and pass in .yml file

**Comment by mbe9477** [comment]
> neo-instabot -c yourconfig.yml -vv
> set your login and pass in .yml file

This is my yml file:
> sample.instabot.config.yml
> ---
> login : "xxx"
> password : "xxx"
> debug: 0
> follow_time: 604800
> like_per_day: 300
> comments_per_day: 70
> max_like_for_one_tag: 36
> follow_per_day: 100
> follow_time: 36000
> unfollow_per_day: 0
> unfollow_break_min: 3
> unfollow_break_max: 17
> unfollow_selebgram: false
> unfollow_probably_fake: true
> unfollow_inactive: true
> unfollow_recent_feed: false

Of course login and password are set there. 
But there is no option to use own hashtags!?

**Comment by soulpawa** [comment]
of course you can use your own hashtags:

tag_list: [hashtag1,hasthag2,hashtag3,hashtag4....]

**Comment by mbe9477** [comment]
That workes now well! Thanks for your help!
