### ISSUE TITLE
log_mod=1 does nothing

### ISSUE THREAD

**Issue by F4bri92** [yurilaaziz/instabot.py#2]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (ArchLinux)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.3
```

#### Pip Version?
```
pip 19.1.1 from /usr/lib/python3.7/site-packages/pip (python 3.7)
```

#### Description of your issue

With latest version with `log_mod=1` the bot does not log to file.

#### Config

```
bot = InstaBot(
    login="",
    password="",
    like_per_day=1000,
        media_min_like=50,
        media_max_like=250,
    tag_list=[],
    tag_blacklist=[],
    user_blacklist={"": ""},
    max_like_for_one_tag=20,
    follow_per_day=0,
    unfollow_per_day=0,
    unlike_per_day=0,
    unfollow_recent_feed=False, # If True, the bot will also unfollow people who dont follow you using the recent feed. Default: True
    session_file="username.session", # Set to False to disable persistent session, or specify custom session_file (ie ='myusername.session')
    comments_per_day=0,
    log_mod=1,
    proxy=""
)
```

**Comment by iamklaus** [comment]
Same for me

**Comment by yurilaaziz** [comment]
please update to the last version,
