### ISSUE TITLE
Calculation of time in day

### ISSUE THREAD

**Issue by marcusagm** [yurilaaziz/instabot.py#6]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [x] Linux (include flavour)
- [ ] Android (include terminal)

```
Linux *** 21-Ubuntu SMP Tue Aug 28 10:23:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.6.8
```

#### Pip Version?
```
pip 9.0.1
```

#### Instabot Version?
```
Installed version 0.5.9
```

#### How you use the instabot
- [x] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
When we indicate a start and end time, the like_delay has to consider only the interval. Currently if the bot doesn't run 24 hours a day, the maximum number of likes will never be reached.
```

change suggestion
```python
# ( he - hs) * 60 * 60 - ms * me
# ( 20 - 8 ) * 60 * 60 - 20 + 40 
self.time_in_day = ( self.end_at_h - self.start_at_h ) * 60 * 60 - self.start_at_m + self.end_at_m

self.like_per_run = int(self.config.get("like_per_run"))
    if self.like_per_run > 0:
        self.like_delay = self.time_in_day / self.like_per_run
```

https://github.com/yurilaaziz/instabot.py/blob/7633395fc7e29109037ee8a4d2ef8655926deec6/instabot_py/instabot.py#L101

**Comment by yurilaaziz** [comment]
thank you for your interest.
I fixed the formula too
